name: Compilar APK con Buildozer

# Se ejecuta cada vez que subís cambios a la rama "main",
# y también podés dispararlo a mano desde la pestaña "Actions" de GitHub.
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/kivy/buildozer:latest
    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4


      - name: Compilar el APK con Buildozer
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
        run: |
          buildozer --version
          buildozer android debug

      - name: Subir el APK como artefacto descargable
        uses: actions/upload-artifact@v4
        with:
          name: diccionariotarot-apk
          path: bin/*.apk
      
      